name: Build and Test ChaoticodePlus

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. Upgrade pip and install build tools
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      # 4. Build the package
      - name: Build package
        run: python -m build

      # 5. Test installing the package
      - name: Install package locally
        run: pip install dist/*.whl

      # 6. Run a simple CC+ test
      - name: Test CC_plus function
        run: |
          python -c "from chaoticodeplus import CC_plus; CC_plus('pofjjiojo0jigb'*1+'oapofapfedpo')"
